DROP TABLE IF EXISTS DESKTOPS;
DROP TABLE IF EXISTS HDDS;
DROP TABLE IF EXISTS LAPTOPS;
DROP TABLE IF EXISTS MONITORS;

DROP SEQUENCE IF EXISTS DESKTOP_ID_GENERATOR;
DROP SEQUENCE IF EXISTS HDD_ID_GENERATOR;
DROP SEQUENCE IF EXISTS LAPTOP_ID_GENERATOR;
DROP SEQUENCE IF EXISTS MONITOR_ID_GENERATOR;

create sequence DESKTOP_ID_GENERATOR;
create sequence HDD_ID_GENERATOR;
create sequence LAPTOP_ID_GENERATOR;
create sequence MONITOR_ID_GENERATOR;

CREATE TABLE DESKTOPS (
    DESKTOP_ID  VARCHAR(64) default DESKTOP_ID_GENERATOR.nextval,
    SERIAL_NUMBER     VARCHAR(128),
    MANUFACTURER  VARCHAR(64),
    PRICE    DECIMAL(20, 2),
    CURRENCY VARCHAR(64),
    AMOUNT    DOUBLE,
    FORM_FACTOR VARCHAR(64)
);

CREATE TABLE HDDS (
    HDD_ID  VARCHAR(64) default HDD_ID_GENERATOR.nextval,
    SERIAL_NUMBER     VARCHAR(128),
    MANUFACTURER  VARCHAR(64),
    PRICE    DECIMAL(20, 2),
    CURRENCY VARCHAR(64),
    AMOUNT    DOUBLE,
    VOLUME DOUBLE
);

CREATE TABLE LAPTOPS (
    LAPTOP_ID  VARCHAR(64) default LAPTOP_ID_GENERATOR.nextval,
    SERIAL_NUMBER     VARCHAR(128),
    MANUFACTURER  VARCHAR(64),
    PRICE    DECIMAL(20, 2),
    CURRENCY VARCHAR(64),
    AMOUNT    DOUBLE,
    LAPTOP_SIZE DOUBLE
);

CREATE TABLE MONITORS (
    MONITOR_ID  VARCHAR(64) default MONITOR_ID_GENERATOR.nextval,
    SERIAL_NUMBER     VARCHAR(128),
    MANUFACTURER  VARCHAR(64),
    PRICE    DECIMAL(20, 2),
    CURRENCY VARCHAR(64),
    AMOUNT    DOUBLE,
    DIAGONAL DOUBLE
);