CREATE SEQUENCE IF NOT EXISTS DESKTOP_ID_GENERATOR;
CREATE SEQUENCE IF NOT EXISTS HDD_ID_GENERATOR;
CREATE SEQUENCE IF NOT EXISTS LAPTOP_ID_GENERATOR;
CREATE SEQUENCE IF NOT EXISTS MONITOR_ID_GENERATOR;

CREATE TABLE IF NOT EXISTS DESKTOPS (
    DESKTOP_ID  VARCHAR(64) default DESKTOP_ID_GENERATOR.nextval,
    SERIAL_NUMBER     VARCHAR(128),
    MANUFACTURER  VARCHAR(64),
    PRICE    DECIMAL(20, 2),
    CURRENCY VARCHAR(64),
    AMOUNT    DOUBLE,
    FORM_FACTOR VARCHAR(64)
);

CREATE TABLE IF NOT EXISTS HDDS (
    HDD_ID  VARCHAR(64) default HDD_ID_GENERATOR.nextval,
    SERIAL_NUMBER     VARCHAR(128),
    MANUFACTURER  VARCHAR(64),
    PRICE    DECIMAL(20, 2),
    CURRENCY VARCHAR(64),
    AMOUNT    DOUBLE,
    VOLUME DOUBLE
);

CREATE TABLE IF NOT EXISTS LAPTOPS (
    LAPTOP_ID  VARCHAR(64) default LAPTOP_ID_GENERATOR.nextval,
    SERIAL_NUMBER     VARCHAR(128),
    MANUFACTURER  VARCHAR(64),
    PRICE    DECIMAL(20, 2),
    CURRENCY VARCHAR(64),
    AMOUNT    DOUBLE,
    LAPTOP_SIZE DOUBLE
);

CREATE TABLE IF NOT EXISTS MONITORS (
    MONITOR_ID  VARCHAR(64) default MONITOR_ID_GENERATOR.nextval,
    SERIAL_NUMBER     VARCHAR(128),
    MANUFACTURER  VARCHAR(64),
    PRICE    DECIMAL(20, 2),
    CURRENCY VARCHAR(64),
    AMOUNT    DOUBLE,
    DIAGONAL DOUBLE
);